from enum import StrEnum


class Role(StrEnum):
    OWNER = "OWNER"
    ADMIN = "ADMIN"
    MANAGER = "MANAGER"
    STAFF = "STAFF"
    TECHNICIAN = "TECHNICIAN"
    ACCOUNTANT = "ACCOUNTANT"
    READ_ONLY = "READ_ONLY"


class Permission(StrEnum):
    READ_CUSTOMERS = "READ_CUSTOMERS"
    CREATE_CUSTOMER = "CREATE_CUSTOMER"
    UPDATE_CUSTOMER = "UPDATE_CUSTOMER"
    READ_JOBS = "READ_JOBS"
    CREATE_JOB = "CREATE_JOB"
    SCHEDULE_JOB = "SCHEDULE_JOB"
    APPROVE_SPEND = "APPROVE_SPEND"
    CREATE_INVOICE = "CREATE_INVOICE"
    SEND_INVOICE = "SEND_INVOICE"
    # Phase 14: quotes/estimates. Reading a quote reuses VIEW_FINANCIALS
    # (same tier as reading an invoice) rather than a new READ_QUOTES.
    CREATE_QUOTE = "CREATE_QUOTE"
    SEND_QUOTE = "SEND_QUOTE"
    COLLECT_PAYMENT = "COLLECT_PAYMENT"
    VIEW_FINANCIALS = "VIEW_FINANCIALS"
    RUN_MARKETING = "RUN_MARKETING"
    SEND_CUSTOMER_MESSAGE = "SEND_CUSTOMER_MESSAGE"
    MANAGE_INTEGRATIONS = "MANAGE_INTEGRATIONS"
    MANAGE_USERS = "MANAGE_USERS"
    EXECUTE_AI_ACTION = "EXECUTE_AI_ACTION"
    DELETE_CUSTOMER = "DELETE_CUSTOMER"
    READ_LEADS = "READ_LEADS"
    CREATE_LEAD = "CREATE_LEAD"
    UPDATE_LEAD = "UPDATE_LEAD"
    QUALIFY_LEAD = "QUALIFY_LEAD"
    READ_APPOINTMENTS = "READ_APPOINTMENTS"
    CREATE_APPOINTMENT = "CREATE_APPOINTMENT"
    CANCEL_APPOINTMENT = "CANCEL_APPOINTMENT"
    UPDATE_JOB = "UPDATE_JOB"
    ASSIGN_JOB = "ASSIGN_JOB"
    DISPATCH_JOB = "DISPATCH_JOB"
    MANAGE_TASKS = "MANAGE_TASKS"
    MANAGE_MATERIALS = "MANAGE_MATERIALS"
    UPLOAD_JOB_ATTACHMENT = "UPLOAD_JOB_ATTACHMENT"
    MANAGE_QA = "MANAGE_QA"
    MANAGE_EXCEPTIONS = "MANAGE_EXCEPTIONS"
    APPROVE_SCOPE_CHANGE = "APPROVE_SCOPE_CHANGE"
    CLOSE_JOB = "CLOSE_JOB"
    DELETE_JOB = "DELETE_JOB"
    UPDATE_INVOICE = "UPDATE_INVOICE"
    APPROVE_INVOICE = "APPROVE_INVOICE"
    VOID_INVOICE = "VOID_INVOICE"
    RECORD_PAYMENT = "RECORD_PAYMENT"
    APPROVE_REFUND = "APPROVE_REFUND"
    APPROVE_CREDIT_NOTE = "APPROVE_CREDIT_NOTE"
    APPROVE_WRITEOFF = "APPROVE_WRITEOFF"
    MANAGE_JOB_COSTS = "MANAGE_JOB_COSTS"
    MANAGE_VENDORS = "MANAGE_VENDORS"
    MANAGE_COLLECTIONS = "MANAGE_COLLECTIONS"
    VIEW_CASH_FORECAST = "VIEW_CASH_FORECAST"
    READ_MARKETING = "READ_MARKETING"
    MANAGE_CAMPAIGNS = "MANAGE_CAMPAIGNS"
    MANAGE_MARKETING_CONTENT = "MANAGE_MARKETING_CONTENT"
    APPROVE_MARKETING_CONTENT = "APPROVE_MARKETING_CONTENT"
    MANAGE_OUTBOUND = "MANAGE_OUTBOUND"
    MANAGE_NURTURE = "MANAGE_NURTURE"
    MANAGE_REACTIVATION = "MANAGE_REACTIVATION"
    VIEW_MARKETING_ANALYTICS = "VIEW_MARKETING_ANALYTICS"
    READ_RETENTION = "READ_RETENTION"
    MANAGE_RETENTION = "MANAGE_RETENTION"
    MANAGE_RETENTION_CAMPAIGNS = "MANAGE_RETENTION_CAMPAIGNS"
    SEND_RETENTION_COMMUNICATION = "SEND_RETENTION_COMMUNICATION"
    MANAGE_REVIEWS = "MANAGE_REVIEWS"
    MANAGE_REFERRALS = "MANAGE_REFERRALS"
    APPROVE_REFERRAL_REWARD = "APPROVE_REFERRAL_REWARD"
    VIEW_CUSTOMER_HEALTH = "VIEW_CUSTOMER_HEALTH"
    VIEW_REFERRAL_ANALYTICS = "VIEW_REFERRAL_ANALYTICS"
    READ_EVENTS = "READ_EVENTS"
    MANAGE_EVENTS = "MANAGE_EVENTS"
    READ_MORNING_BRIEF = "READ_MORNING_BRIEF"
    GENERATE_MORNING_BRIEF = "GENERATE_MORNING_BRIEF"
    EXECUTE_RECOMMENDATION = "EXECUTE_RECOMMENDATION"
    READ_APPROVALS = "READ_APPROVALS"
    APPROVE_ACTIONS = "APPROVE_ACTIONS"
    REJECT_ACTIONS = "REJECT_ACTIONS"
    EXECUTE_APPROVED_ACTIONS = "EXECUTE_APPROVED_ACTIONS"
    READ_AI_ACTIVITY = "READ_AI_ACTIVITY"
    READ_AUTOMATION_POLICIES = "READ_AUTOMATION_POLICIES"
    MANAGE_AUTOMATION_POLICIES = "MANAGE_AUTOMATION_POLICIES"
    READ_KNOWLEDGE = "READ_KNOWLEDGE"
    MANAGE_KNOWLEDGE = "MANAGE_KNOWLEDGE"
    READ_NOTIFICATIONS = "READ_NOTIFICATIONS"
    MANAGE_NOTIFICATION_PREFERENCES = "MANAGE_NOTIFICATION_PREFERENCES"
    READ_VOICE_CALLS = "READ_VOICE_CALLS"
    MANAGE_VOICE_SETTINGS = "MANAGE_VOICE_SETTINGS"
    READ_AUTOMATIONS = "READ_AUTOMATIONS"
    MANAGE_AUTOMATIONS = "MANAGE_AUTOMATIONS"
    READ_MEMORY = "READ_MEMORY"
    MANAGE_MEMORY = "MANAGE_MEMORY"
    READ_COMPLIANCE = "READ_COMPLIANCE"
    MANAGE_COMPLIANCE = "MANAGE_COMPLIANCE"


# Permission matrix: role -> allowed permissions.
# OWNER/ADMIN get everything; DELETE_CUSTOMER is OWNER-only (section 4/10: destructive ops are
# BLOCKED or OWNER ONLY).
_ALL_PERMISSIONS = set(Permission)

ROLE_PERMISSIONS: dict[Role, set[Permission]] = {
    Role.OWNER: _ALL_PERMISSIONS,
    Role.ADMIN: _ALL_PERMISSIONS - {Permission.DELETE_CUSTOMER},
    Role.MANAGER: {
        Permission.READ_CUSTOMERS,
        Permission.CREATE_CUSTOMER,
        Permission.UPDATE_CUSTOMER,
        Permission.READ_JOBS,
        Permission.CREATE_JOB,
        Permission.SCHEDULE_JOB,
        Permission.CREATE_INVOICE,
        Permission.SEND_INVOICE,
        Permission.CREATE_QUOTE,
        Permission.SEND_QUOTE,
        Permission.VIEW_FINANCIALS,
        Permission.RUN_MARKETING,
        Permission.SEND_CUSTOMER_MESSAGE,
        Permission.EXECUTE_AI_ACTION,
        Permission.READ_LEADS,
        Permission.CREATE_LEAD,
        Permission.UPDATE_LEAD,
        Permission.QUALIFY_LEAD,
        Permission.READ_APPOINTMENTS,
        Permission.CREATE_APPOINTMENT,
        Permission.CANCEL_APPOINTMENT,
        Permission.UPDATE_JOB,
        Permission.ASSIGN_JOB,
        Permission.DISPATCH_JOB,
        Permission.MANAGE_TASKS,
        Permission.MANAGE_MATERIALS,
        Permission.UPLOAD_JOB_ATTACHMENT,
        Permission.MANAGE_QA,
        Permission.MANAGE_EXCEPTIONS,
        Permission.APPROVE_SCOPE_CHANGE,
        Permission.CLOSE_JOB,
        Permission.UPDATE_INVOICE,
        Permission.APPROVE_INVOICE,
        Permission.VOID_INVOICE,
        Permission.RECORD_PAYMENT,
        Permission.APPROVE_REFUND,
        Permission.APPROVE_CREDIT_NOTE,
        Permission.APPROVE_WRITEOFF,
        Permission.MANAGE_JOB_COSTS,
        Permission.MANAGE_VENDORS,
        Permission.MANAGE_COLLECTIONS,
        Permission.VIEW_CASH_FORECAST,
        Permission.READ_MARKETING,
        Permission.MANAGE_CAMPAIGNS,
        Permission.MANAGE_MARKETING_CONTENT,
        Permission.APPROVE_MARKETING_CONTENT,
        Permission.MANAGE_OUTBOUND,
        Permission.MANAGE_NURTURE,
        Permission.MANAGE_REACTIVATION,
        Permission.VIEW_MARKETING_ANALYTICS,
        Permission.READ_RETENTION,
        Permission.MANAGE_RETENTION,
        Permission.MANAGE_RETENTION_CAMPAIGNS,
        Permission.SEND_RETENTION_COMMUNICATION,
        Permission.MANAGE_REVIEWS,
        Permission.MANAGE_REFERRALS,
        Permission.APPROVE_REFERRAL_REWARD,
        Permission.VIEW_CUSTOMER_HEALTH,
        Permission.VIEW_REFERRAL_ANALYTICS,
        Permission.READ_EVENTS,
        Permission.MANAGE_EVENTS,
        Permission.READ_MORNING_BRIEF,
        Permission.GENERATE_MORNING_BRIEF,
        Permission.EXECUTE_RECOMMENDATION,
        Permission.READ_APPROVALS,
        Permission.APPROVE_ACTIONS,
        Permission.REJECT_ACTIONS,
        Permission.EXECUTE_APPROVED_ACTIONS,
        Permission.READ_AI_ACTIVITY,
        Permission.READ_AUTOMATION_POLICIES,
        Permission.MANAGE_AUTOMATION_POLICIES,
        Permission.READ_NOTIFICATIONS,
        Permission.MANAGE_NOTIFICATION_PREFERENCES,
        Permission.READ_KNOWLEDGE,
        Permission.MANAGE_KNOWLEDGE,
        Permission.READ_VOICE_CALLS,
        Permission.MANAGE_VOICE_SETTINGS,
        Permission.READ_AUTOMATIONS,
        Permission.MANAGE_AUTOMATIONS,
        Permission.READ_MEMORY,
        Permission.MANAGE_MEMORY,
        Permission.READ_COMPLIANCE,
        Permission.MANAGE_COMPLIANCE,
    },
    Role.STAFF: {
        Permission.READ_CUSTOMERS,
        Permission.CREATE_CUSTOMER,
        Permission.UPDATE_CUSTOMER,
        Permission.READ_JOBS,
        Permission.CREATE_JOB,
        Permission.SCHEDULE_JOB,
        Permission.SEND_CUSTOMER_MESSAGE,
        Permission.READ_LEADS,
        Permission.CREATE_LEAD,
        Permission.UPDATE_LEAD,
        Permission.READ_APPOINTMENTS,
        Permission.CREATE_APPOINTMENT,
        Permission.CANCEL_APPOINTMENT,
        Permission.UPDATE_JOB,
        Permission.MANAGE_TASKS,
        Permission.MANAGE_MATERIALS,
        Permission.UPLOAD_JOB_ATTACHMENT,
    },
    Role.TECHNICIAN: {
        Permission.READ_JOBS,
        Permission.SCHEDULE_JOB,
        Permission.READ_CUSTOMERS,
        Permission.READ_LEADS,
        Permission.READ_APPOINTMENTS,
        Permission.UPDATE_JOB,
        Permission.DISPATCH_JOB,
        Permission.MANAGE_TASKS,
        Permission.UPLOAD_JOB_ATTACHMENT,
        Permission.MANAGE_QA,
    },
    Role.ACCOUNTANT: {
        Permission.VIEW_FINANCIALS,
        Permission.CREATE_INVOICE,
        Permission.UPDATE_INVOICE,
        Permission.SEND_INVOICE,
        Permission.CREATE_QUOTE,
        Permission.SEND_QUOTE,
        Permission.COLLECT_PAYMENT,
        Permission.RECORD_PAYMENT,
        Permission.MANAGE_JOB_COSTS,
        Permission.MANAGE_VENDORS,
        Permission.MANAGE_COLLECTIONS,
        Permission.VIEW_CASH_FORECAST,
        Permission.READ_CUSTOMERS,
        Permission.READ_LEADS,
        Permission.READ_JOBS,
    },
    Role.READ_ONLY: {
        Permission.READ_CUSTOMERS,
        Permission.READ_JOBS,
        Permission.VIEW_FINANCIALS,
        Permission.READ_LEADS,
        Permission.READ_APPOINTMENTS,
        Permission.VIEW_CASH_FORECAST,
        Permission.READ_MARKETING,
        Permission.VIEW_MARKETING_ANALYTICS,
        Permission.READ_RETENTION,
        Permission.VIEW_CUSTOMER_HEALTH,
        Permission.VIEW_REFERRAL_ANALYTICS,
        Permission.READ_EVENTS,
        Permission.READ_MORNING_BRIEF,
        Permission.READ_APPROVALS,
        Permission.READ_AI_ACTIVITY,
        Permission.READ_AUTOMATION_POLICIES,
        Permission.READ_NOTIFICATIONS,
        Permission.READ_KNOWLEDGE,
        Permission.READ_VOICE_CALLS,
        Permission.READ_AUTOMATIONS,
        Permission.READ_MEMORY,
        Permission.READ_COMPLIANCE,
    },
}


def role_has_permission(role: Role, permission: Permission) -> bool:
    return permission in ROLE_PERMISSIONS.get(role, set())
