from fastapi import APIRouter

from app.api.v1 import (
    ai_activity,
    appointments,
    approvals,
    ar,
    auth,
    automation,
    automations,
    billing,
    cash,
    company_memory,
    credit_notes,
    crm,
    customers,
    dashboard,
    events,
    exceptions,
    finance,
    google_calendar,
    google_calendar_oauth,
    integrations,
    invoices,
    job_costs,
    jobs,
    knowledge,
    leads,
    marketing,
    marketing_attribution,
    marketing_campaigns,
    marketing_content,
    marketing_nurture,
    marketing_outbound,
    marketing_reactivation,
    marketing_seo,
    marketplace_webhooks,
    morning_brief,
    notifications,
    operations,
    organizations,
    payments,
    profitability,
    public_contracts,
    public_invites,
    public_leads,
    public_quotes,
    quickbooks_oauth,
    quotes,
    contracts,
    refunds,
    retention,
    retention_campaigns,
    retention_opportunities,
    retention_referrals,
    retention_reminders,
    retention_reviews,
    tools,
    users,
    vendors,
    compliance,
    warranties,
    voice,
    voice_stream,
    webhooks,
    workers,
    writeoffs,
)

api_router = APIRouter(prefix="/api/v1")
api_router.include_router(auth.router)
api_router.include_router(users.router)
api_router.include_router(vendors.router)
api_router.include_router(compliance.router)
api_router.include_router(warranties.router)
api_router.include_router(events.router)
api_router.include_router(tools.router)
api_router.include_router(approvals.router)
api_router.include_router(ai_activity.router)
api_router.include_router(integrations.router)
api_router.include_router(quickbooks_oauth.router)
api_router.include_router(google_calendar_oauth.router)
api_router.include_router(google_calendar.router)
api_router.include_router(leads.router)
api_router.include_router(customers.router)
api_router.include_router(appointments.router)
api_router.include_router(crm.router)
api_router.include_router(dashboard.router)
api_router.include_router(billing.router)
api_router.include_router(jobs.router)
api_router.include_router(workers.router)
api_router.include_router(exceptions.router)
api_router.include_router(operations.router)
api_router.include_router(organizations.router)
api_router.include_router(invoices.router)
api_router.include_router(quotes.router)
api_router.include_router(contracts.router)
api_router.include_router(public_quotes.router)
api_router.include_router(public_contracts.router)
api_router.include_router(public_leads.router)
api_router.include_router(public_invites.router)
api_router.include_router(payments.router)
api_router.include_router(ar.router)
api_router.include_router(refunds.router)
api_router.include_router(credit_notes.router)
api_router.include_router(writeoffs.router)
api_router.include_router(job_costs.router)
api_router.include_router(profitability.router)
api_router.include_router(cash.router)
api_router.include_router(finance.router)
api_router.include_router(marketing_campaigns.router)
api_router.include_router(marketing_attribution.router)
api_router.include_router(marketing_content.router)
api_router.include_router(marketing_seo.router)
api_router.include_router(marketing_outbound.router)
api_router.include_router(marketing_nurture.router)
api_router.include_router(marketing_reactivation.router)
api_router.include_router(marketing.router)
api_router.include_router(retention_opportunities.router)
api_router.include_router(retention_reminders.router)
api_router.include_router(retention_reviews.router)
api_router.include_router(retention_referrals.router)
api_router.include_router(retention_campaigns.router)
api_router.include_router(retention.router)
api_router.include_router(morning_brief.router)
api_router.include_router(automation.router)
api_router.include_router(automations.router)
api_router.include_router(company_memory.router)
api_router.include_router(notifications.router)
api_router.include_router(knowledge.router)
api_router.include_router(webhooks.router)
api_router.include_router(marketplace_webhooks.router)
api_router.include_router(voice.router)
api_router.include_router(voice_stream.router)
